### ISSUE TITLE
lottie preview size too small

### ISSUE THREAD

**Issue by luxurysky** [YangLang116/MediaFilePreviewer#2]
**Describe the bug:**
lottie preview size too small
original size is 1500x3300
{"v":"4.8.0","meta":{"g":"LottieFiles AE 1.0.0","a":"","k":"","d":"","tc":""},"fr":25,"ip":0,"op":50,"w":1500,"h":3300,"nm":"veil_sample","ddd":0,"assets":[{"id":"image_0","w":1643,"h":111,"u":"".......

**Steps to reproduce:** 
-

**Expected behavior:**
want to see larger size.

**Additional context:**
<img width="472" alt="screenshot" src="https://user-images.githubusercontent.com/33050918/185280106-ee13e84d-32e4-4c11-be4f-9a260cce210a.png">

**Comment by YangLang116** [comment]
thank for you to submit issue. this issue will be fixed in next version

**Comment by YangLang116** [comment]
Thanks first, please upgrade the plugin to latest version（v1.0.6)
